In [1]:
import numpy as np
import pandas as pd
import datetime as dt
from pandas_datareader import DataReader
from pandas import Series, DataFrame

In [2]:
filedate = '20220407'

In [3]:
df_stock = pd.read_csv('data/stock_' + filedate + '.csv', index_col=0, header=[0,1], parse_dates=[0])

In [4]:
# 階層構造を逆にすることができます。今回は列方向で試します。
df_stock2 = df_stock.swaplevel('Attributes','Symbols',axis=1)

In [5]:
df_stock2.sort_values(by=['Symbols', 'Attributes'], axis=1, inplace=True)

In [6]:
# マルチインデックスのカラム名を取得する
list = df_stock2.columns.get_level_values('Symbols')

In [7]:
# RSIの計算
def rsi(df):
    # 前日との差分を計算
    df_diff = df[i,"Close"].diff(1)

    # 計算用のDataFrameを定義
    df_up, df_down = df_diff.copy(), df_diff.copy()
    
    # df_upはマイナス値を0に変換
    # df_downはプラス値を0に変換して正負反転
    df_up[df_up < 0] = 0
    df_down[df_down > 0] = 0
    df_down = df_down * -1
    
    # 期間03でそれぞれの平均を算出
    df_up_sma03 = df_up.rolling(window=3, center=False).mean()
    df_down_sma03 = df_down.rolling(window=3, center=False).mean()

    # RSIを算出
    df[i, "RSI"] = 100.0 * (df_up_sma03 / (df_up_sma03 + df_down_sma03))

    return df

for i in list: 
    df_stock2 = rsi(df_stock2)

C:\Users\ricew\AppData\Local\Temp/ipykernel_240656/2502226233.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[i, "RSI"] = 100.0 * (df_up_sma03 / (df_up_sma03 + df_down_sma03))

In [8]:
df_stock2

Symbols          1301.T                                                1332.T  \
Attributes    Adj Close   Close    High     Low    Open    Volume   Adj Close
Date
2022-03-08  3150.862061  3225.0  3270.0  3220.0  3250.0   39600.0  502.598938
2022-03-09  3141.092041  3215.0  3250.0  3215.0  3225.0   20200.0  494.668396
2022-03-10  3189.942627  3265.0  3270.0  3235.0  3260.0   20700.0  530.355896
2022-03-11  3170.402344  3245.0  3265.0  3220.0  3220.0   21300.0  533.329834
2022-03-14  3165.517334  3240.0  3270.0  3200.0  3200.0   23400.0  555.138855
2022-03-15  3189.942627  3265.0  3290.0  3230.0  3230.0   21500.0  561.086792
2022-03-16  3233.907959  3310.0  3315.0  3280.0  3285.0   36000.0  558.112854
2022-03-17  3272.988525  3350.0  3350.0  3300.0  3350.0   37100.0  565.052063
2022-03-18  3316.954102  3395.0  3395.0  3355.0  3395.0   68700.0  560.095459
2022-03-22  3321.839111  3400.0  3460.0  3400.0  3415.0   63900.0  565.052063
2022-03-23  3400.000000  3480.0  3480.0  3420.0  3440.0   44500.0  575.956604
2022-03-24  3390.229980  3470.0  3475.0  3450.0  3475.0   39200.0  565.052063
2022-03-25  3453.735596  3535.0  3565.0  3470.0  3500.0  101400.0  572.982605
2022-03-28  3429.310303  3510.0  3575.0  3505.0  3560.0  107700.0  577.939209
2022-03-29  3400.000000  3480.0  3560.0  3460.0  3560.0  132900.0  571.000000
2022-03-30  3355.000000  3355.0  3410.0  3320.0  3400.0   77700.0  558.000000
2022-03-31  3330.000000  3330.0  3400.0  3330.0  3340.0   25800.0  548.000000
2022-04-01  3435.000000  3435.0  3440.0  3300.0  3320.0   36900.0  549.000000
2022-04-04  3420.000000  3420.0  3435.0  3390.0  3435.0   27600.0  555.000000
2022-04-05  3405.000000  3405.0  3425.0  3380.0  3420.0   16000.0  551.000000
2022-04-06  3385.000000  3385.0  3415.0  3380.0  3410.0   16800.0  538.000000
2022-04-07  3330.000000  3330.0  3360.0  3315.0  3350.0   23700.0  540.000000

Symbols                          ...      9984.T      9986.T      9987.T  \
Attributes  Close   High    Low  ...         RSI         RSI         RSI
Date                             ...
2022-03-08  507.0  521.0  505.0  ...         NaN         NaN         NaN
2022-03-09  499.0  505.0  497.0  ...         NaN         NaN         NaN
2022-03-10  535.0  536.0  507.0  ...         NaN         NaN         NaN
2022-03-11  538.0  541.0  531.0  ...   50.746269   57.575758   78.571429
2022-03-14  560.0  564.0  543.0  ...   30.379747   62.318841   52.631579
2022-03-15  566.0  567.0  558.0  ...    0.000000   54.782609   57.142857
2022-03-16  563.0  571.0  559.0  ...   53.813559  100.000000   70.000000
2022-03-17  570.0  572.0  565.0  ...   73.758865   94.285714   82.352941
2022-03-18  565.0  572.0  563.0  ...  100.000000   83.333333   14.285714
2022-03-22  570.0  575.0  568.0  ...  100.000000   63.636364   42.857143
2022-03-23  581.0  582.0  573.0  ...  100.000000  100.000000   75.675676
2022-03-24  570.0  581.0  567.0  ...  100.000000   42.857143   71.794872
2022-03-25  578.0  580.0  570.0  ...   82.156134   30.000000   66.666667
2022-03-28  583.0  584.0  577.0  ...   44.508671    0.000000   18.750000
2022-03-29  576.0  578.0  567.0  ...   51.515152   65.384615   89.473684
2022-03-30  558.0  566.0  546.0  ...  100.000000   58.620690   29.787234
2022-03-31  548.0  555.0  546.0  ...   75.907591   19.540230   24.561404
2022-04-01  549.0  552.0  537.0  ...   66.818182    0.000000   21.818182
2022-04-04  555.0  558.0  548.0  ...   75.585284    0.000000   64.705882
2022-04-05  551.0  554.0  547.0  ...  100.000000    0.000000  100.000000
2022-04-06  538.0  548.0  537.0  ...   68.190476    0.000000   40.000000
2022-04-07  540.0  541.0  531.0  ...   34.872979    0.000000   11.764706

Symbols         9989.T      9990.T      9991.T     9993.T      9994.T  \
Attributes         RSI         RSI         RSI        RSI         RSI
Date
2022-03-08         NaN         NaN         NaN        NaN         NaN
2022-03-09         NaN         NaN         NaN        NaN         NaN
2022-03-10         NaN         NaN         NaN        NaN         NaN
2022-03-11   66.666667   52.631579   84.000000  50.000000   66.666667
2022-03-14   17.751479   66.666667   73.809524  94.285714   81.333333
2022-03-15   33.173077   45.000000   45.000000  93.333333   63.157895
2022-03-16   50.000000   90.000000   75.000000  80.000000  100.000000
2022-03-17  100.000000   94.444444  100.000000  83.720930   55.813953
2022-03-18   75.000000   83.333333  100.000000  71.428571   44.117647
2022-03-22   55.555556   91.666667  100.000000  66.666667   13.636364
2022-03-23   85.185185   94.444444  100.000000  81.818182   48.648649
2022-03-24   63.888889  100.000000  100.000000  56.250000   47.222222
2022-03-25   69.767442  100.000000   45.833333  67.901235  100.000000
2022-03-28   32.000000  100.000000   12.121212  21.276596   59.375000
2022-03-29   80.000000   37.500000   25.641026  77.083333   58.064516
2022-03-30   22.222222    4.761905   29.411765  73.809524    3.896104
2022-03-31   17.777778    0.000000   23.255814  70.454545    4.411765
2022-04-01    0.000000    0.000000   28.260870  27.777778    0.000000
2022-04-04   44.094488   27.272727   27.083333   3.571429   14.634146
2022-04-05   93.103448   68.421053   56.521739  36.363636   43.750000
2022-04-06   60.447761   65.000000    0.000000  14.000000   46.666667
2022-04-07   26.881720   61.111111    0.000000  18.918919   17.777778

Symbols         9995.T      9997.T
Attributes         RSI         RSI
Date
2022-03-08         NaN         NaN
2022-03-09         NaN         NaN
2022-03-10         NaN         NaN
2022-03-11   60.869565   75.000000
2022-03-14   60.869565   86.363636
2022-03-15   43.750000   72.727273
2022-03-16   80.000000   59.259259
2022-03-17  100.000000   71.052632
2022-03-18  100.000000   62.068966
2022-03-22  100.000000  100.000000
2022-03-23   33.333333  100.000000
2022-03-24   66.666667   69.696970
2022-03-25   33.333333   66.666667
2022-03-28   37.500000   23.809524
2022-03-29    0.000000   79.310345
2022-03-30    0.000000   47.368421
2022-03-31   15.789474   66.666667
2022-04-01   12.500000   65.853659
2022-04-04   45.454545   90.000000
2022-04-05   18.181818   90.909091
2022-04-06   13.333333   65.000000
2022-04-07    0.000000   41.935484

[22 rows x 18613 columns]

In [8]:
# High-Lowの計算結果を新たな列として追加
for i in list: 
    df_stock2[i, 'diff'] = df_stock2[i, 'High'] - df_stock2[i, 'Low']
    df_stock2[i, 'eighty'] = df_stock2[i, 'High'] - df_stock2[i, 'diff'] * 0.2
    df_stock2[i, 'twenty'] = df_stock2[i, 'Low'] + df_stock2[i, 'diff'] * 0.2
    df_stock2[i, 'RSI_diff'] = df_stock2[i,"RSI"].diff(1)

C:\Users\ricew\AppData\Local\Temp/ipykernel_72920/2650847954.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df_stock2[i, 'diff'] = df_stock2[i, 'High'] - df_stock2[i, 'Low']
C:\Users\ricew\AppData\Local\Temp/ipykernel_72920/2650847954.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df_stock2[i, 'eighty'] = df_stock2[i, 'High'] - df_stock2[i, 'diff'] * 0.2
C:\Users\ricew\AppData\Local\Temp/ipykernel_72920/2650847954.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df_stock2[i, 'twenty'] = df_stock2[i, 'Low'] + df_stock2[i, 'diff'] * 0.2
C:\Users\ricew\AppData\Local\Temp/ipykernel_72920/2650847954.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df_stock2[i, 'RSI_diff'] = df_stock2[i,"RSI"].diff(1)

In [9]:
df_stock2.sort_values(by=['Symbols', 'Attributes'], axis=1, inplace=True)

In [10]:
# 日付の比較Datetimeから最後の日のみを取得
df_stock3 = df_stock2.tail(1)

In [11]:
df_stock3 = df_stock3.T

In [12]:
df_stock3 = df_stock3.pivot_table(index=['Symbols'], columns=['Attributes'])

In [13]:
df_stock3 = df_stock3.droplevel(0, axis=1)

In [14]:
# 日付の比較Datetimeから日付のみを取得して比較
df_stock4 = df_stock3[(df_stock3['RSI'] < 30) &
                 (df_stock3['Open'] >= df_stock3['eighty']) &
                 (df_stock3['Close'] <= df_stock3['twenty'])
                 ]

In [15]:
# 日付の比較Datetimeから日付のみを取得して比較
df_stock5 = df_stock3[(df_stock3['RSI'] > 70) &
                 (df_stock3['Close'] >= df_stock3['eighty']) &
                 (df_stock3['Open'] <= df_stock3['twenty'])
                 ]

In [16]:
df_stock4.to_csv('data/pin_80_20_買い_' + filedate + '.csv')

In [17]:
df_stock5.to_csv('data/pin_80_20_売り_' + filedate + '.csv')