In [1]:
import numpy as np
import pandas as pd
import datetime as dt
from pandas_datareader import DataReader
from pandas import Series, DataFrame

In [2]:
filedate = '20220513'

In [3]:
# 01通期財務データ（出典:https://irbank.net/download）
df_balance = pd.read_csv('data/finance/fy-balance-sheet.csv', index_col=0, header=[1], parse_dates=[0])

In [4]:
# 02通期CFデータ（出典:https://irbank.net/download）
df_cashflow = pd.read_csv('data/finance/fy-cash-flow-statement.csv', index_col=0, header=[1], parse_dates=[0])

In [5]:
# 03通期業績データ（出典:https://irbank.net/download）
df_profit_fy = pd.read_csv('data/finance/fy-profit-and-loss.csv', index_col=0, header=[1], parse_dates=[0])

In [6]:
# 04通期配当データ（出典:https://irbank.net/download）
df_dividend = pd.read_csv('data/finance/fy-stock-dividend.csv', index_col=0, header=[1], parse_dates=[0])

In [7]:
# 05四半期売上データ（出典:https://irbank.net/download）
# df_netsales = pd.read_csv('data/finance/qq-yoy-net-sales.csv', index_col=0, header=[3], parse_dates=[0])

In [8]:
# 06四半期営業データ（出典:https://irbank.net/download）
# df_operating = pd.read_csv('data/finance/qq-yoy-operating-income.csv', index_col=0, header=[3], parse_dates=[0])

In [9]:
# 07四半期経常データ（出典:https://irbank.net/download）
# df_ordinary = pd.read_csv('data/finance/qq-yoy-ordinary-income.csv', index_col=0, header=[3], parse_dates=[0])

In [10]:
# 08四半期純利データ（出典:https://irbank.net/download）
# df_profit_pp = pd.read_csv('data/finance/qq-yoy-profit-loss.csv', index_col=0, header=[3], parse_dates=[0])

In [11]:
print(df_balance.shape)
print(df_cashflow.shape)
print(df_profit_fy.shape)
print(df_dividend.shape)
# print(df_netsales.shape)
# print(df_operating.shape)
# print(df_ordinary.shape)
# print(df_profit_pp.shape)

(3954, 9)
(3957, 7)
(3954, 8)
(3674, 7)

In [12]:
# データの結合
df_stock = pd.concat([df_balance, df_cashflow, df_profit_fy, df_dividend
#          ,df_netsales, df_operating, df_ordinary, df_profit_pp
                     ],axis='columns')

In [13]:
pd.set_option('display.max_rows', 60) 
# defult:60,制限なし:None
pd.set_option('display.max_columns', None) 
# defult:20,制限なし:None
df_stock

,年度,総資産,純資産,株主資本,利益剰余金,短期借入金,長期借入金,BPS,自己資本比率,年度,営業CF,投資CF,財務CF,設備投資,現金同等物,営業CFマージン,年度,売上高,営業利益,経常利益,純利益,EPS,ROE,ROA,年度,一株配当,剰余金の配当,自社株買い,配当性向,総還元性向,純資産配当率
コード,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1301,2021/03,1.163310e+11,3.997500e+10,35300000000,28737000000,8056000000,32720000000,3753.75,34.7,2021/03,5997000000,-527000000,-4627000000,-,7097000000,2.41,2021/03,249197000000,4657000000,4879000000,3.838000e+09,356.90,9.5,3.3,2021/03,80,754000000,82000000,19.65,21.78,2.4
1332,2022/03,5.057310e+11,2.085980e+11,172889000000,121472000000,83197000000,94939000000,609.82,37.5,2022/03,29118000000,-17260000000,-11265000000,-18490000000,15683000000,4.2,2022/03,693682000000,27076000000,32372000000,1.727500e+10,55.51,9.1,3.42,2022/03,14,3583000000,2000000,20.74,20.75,2.4
1333,2022/03,5.486030e+11,1.878950e+11,153291000000,91611000000,138467000000,112136000000,3043.95,29.2,2022/03,19249000000,-10258000000,-17200000000,-14818000000,24430000000,2.22,2022/03,866702000000,23819000000,27596000000,1.689800e+10,321.12,10.55,3.08,2022/03,55,2104000000,4000000,12.45,12.47,1.9
1352,2021/03,4.138800e+10,7.855000e+09,6946000000,3243000000,1900000000,18787000000,834.05,16.9,2021/03,4367000000,-1817000000,-662000000,-611000000,4009000000,5.24,2021/03,83265000000,1230000000,1163000000,7.980000e+08,95.30,11.43,1.93,2021/03,20,167000000,-,20.93,-,2.4
1375,2022/03,3.609600e+10,1.047000e+10,10471000000,16411000000,-,17314000000,262.62,29.0,2022/03,5606000000,-2554000000,-3107000000,-2564000000,3723000000,11.91,2022/03,47081000000,4975000000,-,2.989000e+09,74.90,28.55,8.28,2022/03,30,1673000000,48000000,55.97,57.58,12.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9993,2022/02,4.937300e+10,2.881200e+10,28778000000,24247000000,3000000000,1039000000,2641.63,58.3,2022/02,2253000000,-3113000000,-699000000,-2856000000,5721000000,2.04,2022/02,110673000000,1100000000,1161000000,3.680000e+08,33.76,1.28,0.75,2022/02,27,294000000,-,79.89,-,1
9994,2022/03,6.097700e+10,2.908400e+10,27256000000,18202000000,10000000000,3057000000,2532.46,45.0,2022/03,4441000000,-494000000,1180000000,-1054000000,13791000000,3.1,2022/03,143420000000,643000000,8781000000,4.401000e+09,405.93,16.03,7.22,2022/03,50,542000000,-,12.32,-,2.1
9995,2021/03,3.365300e+10,2.250100e+10,22021000000,13184000000,3197000000,310000000,924.83,66.9,2021/03,-2591000000,-356000000,1260000000,-77000000,3395000000,-4.33,2021/03,59861000000,-493000000,-261000000,-3.670000e+08,-15.15,-,-,2021/03,12,312000000,-,-,-,1.3
9996,2022/03,3.131300e+10,2.362700e+10,23557079000,21708541000,683000000,-,2832.91,75.5,2022/03,809000000,-99000000,-1079000000,-624970000,11380076000,2.08,2022/03,38851000000,856000000,1004000000,6.280000e+08,71.35,2.66,2.01,2022/03,30,268215000,810061000,42.71,171.7,1.1
9997,2021/03,2.402110e+11,1.132310e+11,115752000000,94667000000,5909000000,56797000000,1164.96,46.9,2021/03,20772000000,-5185000000,-6996000000,-8236000000,30958000000,10.06,2021/03,206499000000,15734000000,16872000000,1.103600e+10,114.17,9.8,4.59,2021/03,16.5,1546000000,-,14.01,14.01,1.5

In [14]:
# "年度"列を削除※複数ある場合、一斉に削除
df_stock.drop(columns=['年度'], inplace=True)

In [15]:
# "-"をNaNに置換する
df_stock2 = df_stock.replace({'-':np.nan})
# すべて数値形式に変換
df_stock3 = df_stock2.astype(float, errors = 'raise')

In [16]:
# データチェック(Nullがあるか否か)
# df_stock3.isnull().any()
df_stock3.drop(df_stock3.index[df_stock3['総資産'].isnull()], inplace=True)

In [17]:
# df_stock3.index[df_stock3['株主資本'].isnull()]
# NaNがある行を削除
df_stock3.drop(df_stock3.index[df_stock3['株主資本'].isnull()], inplace=True)

In [18]:
# df_stock3.index[df_stock3['利益剰余金'].isnull()]
# NaNがある行を削除
df_stock3.drop(df_stock3.index[df_stock3['利益剰余金'].isnull()], inplace=True)

In [19]:
# df_stock3.index[df_stock3['短期借入金'].isnull()]
# NaNを0に置換
df_stock3['短期借入金'] = df_stock3['短期借入金'].replace(np.nan,0)

In [20]:
# df_stock3.index[df_stock3['長期借入金'].isnull()]
# NaNを0に置換
df_stock3['長期借入金'] = df_stock3['長期借入金'].replace(np.nan,0)

In [21]:
# df_stock3.index[df_stock3['営業CF'].isnull()]
# NaNがある行を削除
df_stock3.drop(df_stock3.index[df_stock3['営業CF'].isnull()], inplace=True)

In [22]:
# df_stock3.index[df_stock3['投資CF'].isnull()]
# NaNがある行を削除
df_stock3.drop(df_stock3.index[df_stock3['投資CF'].isnull()], inplace=True)

In [23]:
# df_stock3.index[df_stock3['財務CF'].isnull()]
# NaNがある行を削除
df_stock3.drop(df_stock3.index[df_stock3['財務CF'].isnull()], inplace=True)

In [24]:
# df_stock3.index[df_stock3['設備投資'].isnull()]
# NaNを0に置換
df_stock3['設備投資'] = df_stock3['設備投資'].replace(np.nan,0)

In [25]:
# df_stock3.index[df_stock3['現金同等物'].isnull()]
# df_stock3.index[df_stock3['営業CFマージン'].isnull()]
# df_stock3.index[df_stock3['売上高'].isnull()]
# df_stock3.index[df_stock3['営業利益'].isnull()]
df_stock3['営業利益'] = df_stock3['営業利益'].fillna(df_stock3['売上高'] * (df_stock3['営業利益'].mean() / df_stock3['売上高'].mean()))

In [26]:
# df_stock3.index[df_stock3['経常利益'].isnull()]
df_stock3['経常利益'] = df_stock3['経常利益'].fillna(df_stock3['売上高'] * (df_stock3['経常利益'].mean() / df_stock3['売上高'].mean()))

In [27]:
# EPS,ROE,ROA
# df_stock3.index[df_stock3['EPS'].isnull()]
# df_stock3.index[df_stock3['ROE'].isnull()]
# NaNがある行を削除
df_stock3.drop(df_stock3.index[df_stock3['ROE'].isnull()], inplace=True)

In [28]:
# df_stock3.index[df_stock3['ROA'].isnull()]
# df_stock3.index[df_stock3['一株配当'].isnull()]
# NaNを0に置換
df_stock3['一株配当'] = df_stock3['一株配当'].replace(np.nan,0)

In [29]:
# df_stock3.index[df_stock3['剰余金の配当'].isnull()]
# NaNを0に置換
df_stock3['剰余金の配当'] = df_stock3['剰余金の配当'].replace(np.nan,0)
df_stock3['自社株買い'] = df_stock3['自社株買い'].replace(np.nan,0)
df_stock3['配当性向'] = df_stock3['配当性向'].replace(np.nan,0)
df_stock3['総還元性向'] = df_stock3['総還元性向'].replace(np.nan,0)
df_stock3['純資産配当率'] = df_stock3['純資産配当率'].replace(np.nan,0)

In [30]:
# データチェック
df_stock3.isnull().any()

総資産         False
純資産         False
株主資本        False
利益剰余金       False
短期借入金       False
長期借入金       False
BPS         False
自己資本比率      False
営業CF        False
投資CF        False
財務CF        False
設備投資        False
現金同等物       False
営業CFマージン     True
売上高          True
営業利益        False
経常利益        False
純利益         False
EPS         False
ROE         False
ROA         False
一株配当        False
剰余金の配当      False
自社株買い       False
配当性向        False
総還元性向       False
純資産配当率      False
dtype: bool

In [31]:
df_stock3.to_csv('data/finance_' + filedate + '.csv')

In [32]:
import sqlalchemy as sa
import pymysql

In [33]:
# Mysqlへ接続
url = 'mysql+pymysql://cyamaryan:python@localhost:13306/stock?charset=utf8mb4'
# engineの作成
engine = sa.create_engine(url, echo=False)

In [34]:
# TABLE(kb_finance)の作成/銘柄リスト
def insertdb(filedate):
    # 日付をDate形式に変換
    trading_date = pd.to_datetime(filedate)
    #インデックスをリセット
    df_insert = df_stock3.reset_index()
    # 列名を置換え
    df_insert = df_insert.rename(columns={'コード':'code', 'trading_date':'trading_date', '年度':'fiscal_year', '総資産':'total_assets', '純資産':'net_assets', '株主資本':'shareholders_equity', '利益剰余金':'retained_earnings', '短期借入金':'loans_payable_short', '長期借入金':'loans_payable_long', 'BPS':'bps', '自己資本比率':'capital_ratio', '営業CF':'cf_from_operating', '投資CF':'cf_from_investment', '財務CF':'cf_from_financial', '設備投資':'capital_spending', '現金同等物':'cash_equivalents', '営業CFマージン':'cf_operating_margin', '売上高':'sales', '営業利益':'operating_income', '経常利益':'ordinary_income', '純利益':'net_income', 'EPS':'eps', 'ROE':'roe', 'ROA':'roa', '一株配当':'dividends', '剰余金の配当':'dividend_of_surplus', '自社株買い':'stock_buybacks', '配当性向':'dpr', '総還元性向':'tpr', '純資産配当率':'doe'})
    # 取得日をセット
    df_insert['trading_date'] = trading_date
    #df.to_sql(<table_name>,con=engine, if_exists='append', index=False)
    df_insert.to_sql('kb_finance',con=engine, if_exists='append', index=False)

In [35]:
insertdb(filedate)